#!/usr/bin/env python3
"""Bundle the shared .dc.html components into _bundle.js so the prototype
runs by double-clicking any page (file://), no local server required.
Re-run after editing any .dc.html file:  python3 build-bundle.py"""
import json, pathlib, urllib.parse

root = pathlib.Path(__file__).parent
components = {}
for f in sorted(root.glob("*.dc.html")):
    name = f.name[: -len(".dc.html")]
    components[f.name] = f.read_text(encoding="utf-8")

js = """// Generated by build-bundle.py - do not edit by hand.
// Serves the prototype's .dc.html pages to the dc runtime from memory, so the
// whole flow works when opened straight from disk (file://) with no server.
(function () {
  var files = %s;
  var realFetch = window.fetch ? window.fetch.bind(window) : null;
  function nameOf(u) {
    var s = String(u && u.url ? u.url : u).split("#")[0].split("?")[0];
    try { s = decodeURIComponent(s); } catch (e) {}
    return s.split("/").pop();
  }
  window.fetch = function (input, init) {
    var n = nameOf(input);
    if (Object.prototype.hasOwnProperty.call(files, n)) {
      return Promise.resolve(new Response(files[n], { status: 200, headers: { "Content-Type": "text/html" } }));
    }
    return realFetch(input, init);
  };
})();
""" % json.dumps(components, ensure_ascii=False)
(root / "_bundle.js").write_text(js, encoding="utf-8")

tag = '<script src="./_bundle.js"></script>\n'
for f in root.glob("*.dc.html"):
    s = f.read_text(encoding="utf-8")
    if "./_bundle.js" not in s:
        s = s.replace('<script src="./support.js"></script>', tag + '<script src="./support.js"></script>', 1)
        f.write_text(s, encoding="utf-8")
print("bundled", len(components), "components")
